name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint & Prettier
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
